version: "3.9"

services:
  app:
    build: ./app
    container_name: python_app
    restart: always
    ports:
      - "8000:8000"
    environment:
      - ENV=production
    volumes:
      - ./app: /app
    networks: 
      - app_network
 
  nginx:
    image: nginx:latest
    container_name: nginx_waf
    restart: always
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      -	./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/modsecurity.conf:/etc/modsecurity/modsecurity.conf:ro
      - ./nginx/crs:/etc/modsecurity/crs:ro
    networks: 
      -	app_network

networks:
  app_network:
    driver: bridge
